// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "url": string;
      "port": number;
      "apikey": string;
      "baseurl": string;
      "model": string;
      "temperature": number;
      "maxtokens": number;
      "useCustomEmbedding": boolean;
      "embeddingUrl": string;
      "embeddingKey": string;
      "embeddingModel": string;
      "batchSize": number;
    };
  }
}
